const BUSINESS = {
  email: 'hello@yazi.ae',
  whatsapp: '971509149431',
  services: { 'مكياج عادي':500, 'مكياج مرافقات':450, 'مكياج سهرة':600, 'مكياج عروس':2100 },
  hairPrice:150, depositRate:.5,
};
const DEFAULT_SETTINGS={slot_buffer_minutes:0,lead_hours:0};
const enc=new TextEncoder();
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const clean=(v,max=1200)=>String(v??'').trim().slice(0,max);
const validDate=s=>/^\d{4}-\d{2}-\d{2}$/.test(s), validTime=s=>/^([01]\d|2[0-3]):[0-5]\d$/.test(s), phoneOk=s=>/^[+\d][\d\s()-]{6,30}$/.test(s);
const nowIso=()=>new Date().toISOString();
function localMinutes(date,time){const [y,m,d]=date.split('-').map(Number),[hh,mm]=time.split(':').map(Number);return Date.UTC(y,m-1,d,hh-4,mm)/60000}
function rangesOverlap(ad,at,bd,bt,dur){if(ad!==bd)return false;if(!dur)return at===bt;const a=localMinutes(ad,at),b=localMinutes(bd,bt),n=Math.max(1,Number(dur)||0);return a<b+n&&b<a+n}
function idFor(kind){const d=new Date(Date.now()+4*3600000).toISOString().slice(2,10).replaceAll('-','');return `${kind==='booking'?'YAZI':'YZM'}-${d}-${crypto.randomUUID().slice(0,4).toUpperCase()}`}
async function sha256(s){return new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(String(s))))}
function b64u(bytes){let x='';for(const b of bytes)x+=String.fromCharCode(b);return btoa(x).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function b64uText(s){return b64u(enc.encode(s))}
function b64uDecodeText(s){s=s.replaceAll('-','+').replaceAll('_','/');while(s.length%4)s+='=';return decodeURIComponent(escape(atob(s)))}
async function hmac(text,secret){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64u(new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(text))))}
function safeEq(a,b){if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
function cookieMap(req){const raw=req.headers.get('cookie')||'';return Object.fromEntries(raw.split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),decodeURIComponent(x.slice(i+1))]}))}
async function issueSession(env){const secret=env.YAZI_SESSION_SECRET;if(!secret||secret.length<24)throw new Error('SESSION_NOT_CONFIGURED');const payload=b64uText(JSON.stringify({exp:Date.now()+8*3600_000,n:crypto.randomUUID()}));return `${payload}.${await hmac(payload,secret)}`}
async function verifySession(req,env){const token=cookieMap(req).yazi_admin;if(!token||!env.YAZI_SESSION_SECRET||!token.includes('.'))return null;const [payload,sig]=token.split('.');const expected=await hmac(payload,env.YAZI_SESSION_SECRET);if(!safeEq(sig,expected))return null;try{const data=JSON.parse(b64uDecodeText(payload));if(!data.exp||data.exp<Date.now())return null;return{token,data}}catch{return null}}
async function csrfFor(token,env){return hmac(`csrf:${token}`,env.YAZI_SESSION_SECRET||'')}
async function requireAdmin(req,env){const session=await verifySession(req,env);if(!session)return{error:json({ok:false,message:'انتهت جلسة الإدارة. سجلي الدخول من جديد.'},401)};if(!['GET','HEAD'].includes(req.method)){const sent=req.headers.get('x-yazi-csrf')||'',expected=await csrfFor(session.token,env);if(!sent||!safeEq(sent,expected))return{error:json({ok:false,message:'طلب غير صالح. أعيدي تحميل لوحة الإدارة.'},403)}}return{session}}
async function body(req){try{return await req.json()}catch{return{}}}
async function settings(db){const r=await db.prepare("SELECT value FROM settings WHERE key='main'").first();try{return{...DEFAULT_SETTINGS,...JSON.parse(r?.value||'{}')}}catch{return{...DEFAULT_SETTINGS}}}
async function activeBookings(db){const r=await db.prepare("SELECT data FROM requests WHERE kind='booking' AND archived=0 AND status NOT IN ('cancelled','archived')").all();return r.results.map(x=>JSON.parse(x.data))}
async function blocks(db){const r=await db.prepare('SELECT * FROM blocks').all();return r.results}
async function checkAvailability(db,date,time){const st=await settings(db);if(localMinutes(date,time)<Date.now()/60000+(Number(st.lead_hours)||0)*60)return{available:false,reason:st.lead_hours?`يجب أن يكون الحجز قبل الموعد بـ ${st.lead_hours} ساعة على الأقل.`:'هذا الموعد مضى. اختاري وقتاً لاحقاً.',settings:st};const [bs,bks]=await Promise.all([blocks(db),activeBookings(db)]);if(bs.some(b=>b.event_date===date&&(b.event_time==='ALL'||b.event_time===time)))return{available:false,reason:'هذا الموعد محجوب وغير متاح.',settings:st};if(bks.some(b=>rangesOverlap(date,time,b.event_date,b.event_time,st.slot_buffer_minutes)))return{available:false,reason:'هذا الوقت محجوز أو قريب من موعد قائم.',settings:st};return{available:true,settings:st}}
function lockKeys(date,time,dur){dur=Number(dur)||0;if(dur<=0)return[`slot/${date}/${time}`];const [h,m]=time.split(':').map(Number),start=Math.floor((h*60+m)/15)*15,end=h*60+m+dur,keys=[];for(let n=start;n<end;n+=15)keys.push(`slot/${date}/${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`);return[...new Set(keys)]}
async function acquireLocks(db,keys,id){try{await db.batch(keys.map(k=>db.prepare('INSERT INTO slot_locks(slot_key,booking_id,created_at) VALUES(?,?,?)').bind(k,id,nowIso())));return true}catch{await db.prepare(`DELETE FROM slot_locks WHERE booking_id=?`).bind(id).run();return false}}
async function releaseLocks(db,keys=[]){if(!keys.length)return;await db.batch(keys.map(k=>db.prepare('DELETE FROM slot_locks WHERE slot_key=?').bind(k)))}
async function rateLimit(req,db){const raw=clean(req.headers.get('cf-connecting-ip')||'unknown',80),hash=b64u(await sha256(raw)).slice(0,24),hour=Math.floor(Date.now()/3600000),key=`${hash}/${hour}`;const row=await db.prepare('SELECT count FROM rate_limits WHERE rate_key=?').bind(key).first();if(Number(row?.count||0)>=12)return false;await db.prepare('INSERT INTO rate_limits(rate_key,count,updated_at) VALUES(?,1,?) ON CONFLICT(rate_key) DO UPDATE SET count=count+1,updated_at=excluded.updated_at').bind(key,nowIso()).run();return true}
function bookingText(b){return [`طلب حجز ${b.id}`,`الاسم: ${b.full_name}`,`الهاتف: ${b.phone}`,`الخدمة: ${b.service}${b.hair?' + شعر':''}`,`الإجمالي: ${b.total_price} د.إ`,`العربون: ${b.deposit_amount} د.إ`,`التاريخ: ${b.event_date}`,`الوقت: ${b.event_time}`,`مكان الخدمة: ${b.location_type==='home'?'موقع العميلة':'الاستوديو'}`,b.city?`المدينة: ${b.city}`:'',b.address?`العنوان: ${b.address}`:'',b.notes?`ملاحظات: ${b.notes}`:''].filter(Boolean).join('\n')}
function modelText(m){return [`طلب مودل ${m.id}`,`الاسم: ${m.full_name}`,`العمر: ${m.age}`,`الهاتف: ${m.phone}`,`المدينة: ${m.city}`,m.instagram?`إنستغرام: ${m.instagram}`:'',m.availability_text?`الأوقات: ${m.availability_text}`:'',m.experience?`الخبرة: ${m.experience}`:'',m.notes?`ملاحظات: ${m.notes}`:''].filter(Boolean).join('\n')}
async function optionalEmail(env,subject,text){if(!env.YAZI_RESEND_API_KEY)return;try{await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.YAZI_RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:env.YAZI_FROM_EMAIL||'YAZI Website <hello@yazi.ae>',to:[BUSINESS.email],subject,text})})}catch{}}
function normalizePassword(v){v=String(v??'').normalize('NFKC').trim();if(v.length>=2&&((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'"))))v=v.slice(1,-1).trim();return v}
async function passwordEq(a,b){return safeEq(b64u(await sha256(normalizePassword(a))),b64u(await sha256(normalizePassword(b))))}
async function saveRequest(db,r){await db.prepare('INSERT INTO requests(id,kind,data,status,archived,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(r.id,r.kind,JSON.stringify(r),r.status,r.archived?1:0,r.created_at,r.updated_at).run()}
async function updateRequest(db,r){await db.prepare('UPDATE requests SET data=?,status=?,archived=?,updated_at=? WHERE id=? AND kind=?').bind(JSON.stringify(r),r.status,r.archived?1:0,r.updated_at,r.id,r.kind).run()}
async function getRequest(db,id,kind){const r=await db.prepare('SELECT data FROM requests WHERE id=? AND kind=?').bind(id,kind).first();return r?JSON.parse(r.data):null}

export async function onRequest({request,env}){
 try{
  if(!env.DB)return json({ok:false,message:'قاعدة بيانات YAZI غير مربوطة بعد.'},503);
  const url=new URL(request.url),action=clean(url.searchParams.get('action'),50),db=env.DB;
  if(request.method==='OPTIONS')return new Response(null,{status:204});
  if(request.method==='GET'&&action==='availability'){const date=clean(url.searchParams.get('date'),10),time=clean(url.searchParams.get('time'),5);if(!validDate(date)||!validTime(time))return json({ok:false,message:'اختاري التاريخ والوقت بشكل صحيح.'},422);const a=await checkAvailability(db,date,time);return json({ok:true,available:a.available,message:a.available?'الموعد متاح مبدئياً ويمكنك إكمال الحجز.':a.reason})}
  if(request.method==='POST'&&action==='booking'){
    if(!(await rateLimit(request,db)))return json({ok:false,message:'تم إرسال عدد كبير من الطلبات. حاولي لاحقاً.'},429);const d=await body(request);if(clean(d.website,50))return json({ok:true,message:'تم الاستلام.'});
    const full_name=clean(d.full_name,120),phone=clean(d.phone,40),service=clean(d.service,80),city=clean(d.city,80),event_date=clean(d.event_date,10),event_time=clean(d.event_time,5),location_type=['studio','home'].includes(d.location_type)?d.location_type:'',address=clean(d.address,220),notes=clean(d.notes,1500),hair=d.hair===true||d.hair==='true'||d.hair==='on';
    if(full_name.length<2||!phoneOk(phone)||!(service in BUSINESS.services)||!validDate(event_date)||!validTime(event_time)||!location_type)return json({ok:false,message:'راجعي الحقول الأساسية قبل إرسال الطلب.'},422);if(location_type==='home'&&address.length<4)return json({ok:false,message:'أضيفي موقع/عنوان تقديم الخدمة.'},422);
    const a=await checkAvailability(db,event_date,event_time);if(!a.available)return json({ok:false,conflict:true,message:a.reason},409);const id=idFor('booking'),locks=lockKeys(event_date,event_time,a.settings.slot_buffer_minutes);if(!(await acquireLocks(db,locks,id)))return json({ok:false,conflict:true,message:'تم حجز هذا الوقت للتو. اختاري وقتاً آخر.'},409);
    const total_price=BUSINESS.services[service]+(hair?BUSINESS.hairPrice:0),r={id,kind:'booking',full_name,phone,service,hair,city,event_date,event_time,location_type,address,notes,total_price,deposit_amount:Math.round(total_price*BUSINESS.depositRate),deposit_status:'unpaid',status:'new',internal_notes:'',archived:false,lock_keys:locks,created_at:nowIso(),updated_at:nowIso()};try{await saveRequest(db,r)}catch(e){await releaseLocks(db,locks);throw e}const text=bookingText(r);optionalEmail(env,`طلب حجز جديد ${id} - YAZI`,text);return json({ok:true,id,message:'تم استلام طلب الحجز بنجاح.',total_price:r.total_price,deposit_amount:r.deposit_amount,whatsapp_url:`https://wa.me/${BUSINESS.whatsapp}?text=${encodeURIComponent(text)}`,email_url:`mailto:${BUSINESS.email}?subject=${encodeURIComponent(`طلب حجز ${id}`)}&body=${encodeURIComponent(text)}`})
  }
  if(request.method==='POST'&&action==='model'){
    if(!(await rateLimit(request,db)))return json({ok:false,message:'تم إرسال عدد كبير من الطلبات. حاولي لاحقاً.'},429);const d=await body(request);if(clean(d.website,50))return json({ok:true,message:'تم الاستلام.'});const full_name=clean(d.full_name,120),phone=clean(d.phone,40),age=Number(d.age),city=clean(d.city,80),instagram=clean(d.instagram,120),availability_text=clean(d.availability_text,500),experience=clean(d.experience,1500),notes=clean(d.notes,1500);if(full_name.length<2||!phoneOk(phone)||!Number.isFinite(age)||age<18||age>70||city.length<2)return json({ok:false,message:'راجعي الحقول الأساسية قبل إرسال الطلب.'},422);const id=idFor('model'),r={id,kind:'model',full_name,phone,age,city,instagram,availability_text,experience,notes,status:'new',internal_notes:'',archived:false,created_at:nowIso(),updated_at:nowIso()};await saveRequest(db,r);const text=modelText(r);optionalEmail(env,`طلب مودل جديد ${id} - YAZI`,text);return json({ok:true,id,message:'تم إرسال طلب التقديم بنجاح.',whatsapp_url:`https://wa.me/${BUSINESS.whatsapp}?text=${encodeURIComponent(text)}`})
  }
  if(request.method==='POST'&&action==='admin_login'){const expected=normalizePassword(env.YAZI_ADMIN_PASSWORD);if(!expected||expected.length<8||!env.YAZI_SESSION_SECRET)return json({ok:false,code:'ADMIN_NOT_CONFIGURED',message:'لوحة الإدارة تحتاج إعداد متغيرات الأمان في Cloudflare أولاً.'},503);const d=await body(request);if(!(await passwordEq(d.password,expected)))return json({ok:false,code:'INVALID_ADMIN_PASSWORD',message:'كلمة المرور لا تطابق القيمة المحفوظة.'},401);const token=await issueSession(env),csrf=await csrfFor(token,env);return json({ok:true,csrf},200,{'Set-Cookie':`yazi_admin=${encodeURIComponent(token)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`})}
  if(request.method==='POST'&&action==='admin_logout'){const a=await requireAdmin(request,env);if(a.error)return a.error;return json({ok:true},200,{'Set-Cookie':'yazi_admin=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'})}
  if(request.method==='GET'&&action==='admin_me'){const a=await requireAdmin(request,env);if(a.error)return a.error;return json({ok:true,csrf:await csrfFor(a.session.token,env)})}
  if(request.method==='GET'&&action==='admin_list'){const a=await requireAdmin(request,env);if(a.error)return a.error;const rows=await db.prepare('SELECT data FROM requests WHERE archived=0 ORDER BY created_at DESC LIMIT 1000').all();return json({ok:true,items:rows.results.map(x=>JSON.parse(x.data))})}
  if(request.method==='POST'&&action==='admin_update'){const a=await requireAdmin(request,env);if(a.error)return a.error;const d=await body(request),id=clean(d.id,40),kind=d.kind==='model'?'model':'booking',r=await getRequest(db,id,kind);if(!r)return json({ok:false,message:'الطلب غير موجود.'},404);const allowed=kind==='booking'?['new','contacted','waiting_deposit','confirmed','completed','cancelled']:['new','contacted','accepted','rejected'],next=clean(d.status,30);if(next&&!allowed.includes(next))return json({ok:false,message:'الحالة غير صحيحة.'},422);if(next){if(r.status!=='cancelled'&&next==='cancelled')await releaseLocks(db,r.lock_keys||[]);if(kind==='booking'&&r.status==='cancelled'&&next!=='cancelled'){const av=await checkAvailability(db,r.event_date,r.event_time);if(!av.available)return json({ok:false,message:'لا يمكن إعادة تفعيل الحجز لأن الموعد لم يعد متاحاً.'},409);const locks=lockKeys(r.event_date,r.event_time,av.settings.slot_buffer_minutes);if(!(await acquireLocks(db,locks,r.id)))return json({ok:false,message:'تعذر إعادة حجز هذا الموعد.'},409);r.lock_keys=locks}r.status=next}if(kind==='booking'&&['unpaid','partial','paid'].includes(d.deposit_status))r.deposit_status=d.deposit_status;if('internal_notes'in d)r.internal_notes=clean(d.internal_notes,2000);r.updated_at=nowIso();await updateRequest(db,r);return json({ok:true,item:r})}
  if(request.method==='POST'&&action==='admin_archive'){const a=await requireAdmin(request,env);if(a.error)return a.error;const d=await body(request),id=clean(d.id,40),kind=d.kind==='model'?'model':'booking',r=await getRequest(db,id,kind);if(!r)return json({ok:false,message:'الطلب غير موجود.'},404);if(kind==='booking')await releaseLocks(db,r.lock_keys||[]);r.archived=true;if(kind==='booking')r.status='cancelled';r.updated_at=nowIso();await updateRequest(db,r);return json({ok:true})}
  if(request.method==='GET'&&action==='admin_blocks'){const a=await requireAdmin(request,env);if(a.error)return a.error;const r=await db.prepare('SELECT * FROM blocks ORDER BY event_date,event_time').all();return json({ok:true,items:r.results})}
  if(request.method==='POST'&&action==='admin_block_add'){const a=await requireAdmin(request,env);if(a.error)return a.error;const d=await body(request),date=clean(d.event_date,10),raw=clean(d.event_time,5),note=clean(d.note,220),time=d.all_day?'ALL':raw;if(!validDate(date)||(time!=='ALL'&&!validTime(time)))return json({ok:false,message:'أدخلي التاريخ والوقت بشكل صحيح.'},422);const id=`BLK-${date}-${time.replace(':','')}-${crypto.randomUUID().slice(0,4)}`;await db.prepare('INSERT INTO blocks(id,event_date,event_time,note,created_at) VALUES(?,?,?,?,?)').bind(id,date,time,note,nowIso()).run();return json({ok:true,item:{id,event_date:date,event_time:time,note}})}
  if(request.method==='POST'&&action==='admin_block_delete'){const a=await requireAdmin(request,env);if(a.error)return a.error;const d=await body(request),id=clean(d.id,80);await db.prepare('DELETE FROM blocks WHERE id=?').bind(id).run();return json({ok:true})}
  if((request.method==='GET'||request.method==='POST')&&action==='admin_settings'){const a=await requireAdmin(request,env);if(a.error)return a.error;if(request.method==='GET')return json({ok:true,settings:await settings(db)});const d=await body(request),s={slot_buffer_minutes:Math.max(0,Math.min(360,Number(d.slot_buffer_minutes)||0)),lead_hours:Math.max(0,Math.min(168,Number(d.lead_hours)||0)),updated_at:nowIso()};await db.prepare("INSERT INTO settings(key,value,updated_at) VALUES('main',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(JSON.stringify(s),s.updated_at).run();return json({ok:true,settings:s})}
  return json({ok:false,message:'المسار غير موجود.'},404)
 }catch(e){console.error('YAZI Cloudflare API error',e);return json({ok:false,message:'حدث خطأ مؤقت في النظام. حاولي مرة أخرى.'},500)}
}
